### ISSUE TITLE
IllegalArgumentException Crash with current Thermal & Ender IO

### ISSUE THREAD

**Issue by WonderDog** [XFactHD/EIORecipesTEInductionSmelter#2]
IllegalArgumentException crash with current version of Ender IO and Thermal Foundation due to hash error.

- EnderCore-1.12.2-0.5.20.jar
- EnderIO-1.12.2-5.0.22.jar   
- ThermalFoundation-1.12.2-2.4.0.14-universal.jar 
- ThermalExpansion-1.12.2-5.4.1.24-universal.jar 
- eiorteis-3.0.jar

[Minecraft Crash Report - EIORecipesTEInductionSmelter](https://pastebin.com/4yeMKrnM)

**Comment by XFactHD** [comment]
This is most likely not on my end as I am only passing objects to ThermalExpansion that I am getting from EnderIO. Please also report this to EnderIO, maybe they have an idea how this is caused.
